/* **** 제약조건 옵션 **********
CASCADE : 부모테이블의 제약조건을 비활성화 (삭제) 시키면서
    참조하고 있는 자녀(SUB) 테이블의 제약조건까지 비활성화(삭제)
*****************************/
--(실습) EMP02, EMP03 외래키(FOREIGN KEY) 이름 변경 처리
---------EMP02 : EMP02_DEPTNO_FK, EMP03: EMP03_DEPTNO_FK
ALTER TABLE EMP02 DROP CONSTRAINT EMP02_DEPTNO_FK;
ALTER TABLE EMP02 ADD CONSTRAINT EMP02_DEPTNO_FK FOREIGN KEY (DEPTNO) REFERENCES DEPT(ID);

ALTER TABLE DEPT DROP CONSTRAINT SYS_C007041;
ALTER TABLE EMP03 ADD CONSTRAINT EMP03_DEPTNO_FK FOREIGN KEY (DEPTNO) REFERENCES DEPT(ID);

ALTER TABLE EMP01 DROP CONSTRAINT EMP01_DEPTNO_FK;
ALTER TABLE EMP01 ADD CONSTRAINT EMP01_DEPTNO_FK FOREIGN KEY(DEPTNO) REFERENCES DEPT(ID);
ALTER TABLE EMP01 
    ADD CONSTRAINT EMP01_DEPTNO_FK 
    FOREIGN KEY (DEPTNO) REFERENCES DEPT(ID);
--DEPT 테이블(부모테이블)의 PRIMARY KEY DISABLE(비활성화) 처리
--cannot disable constraint - dependencies exist
ALTER TABLE DEPT DISABLE PRIMARY KEY;

--방법1 : 자녀테이블의 참조키 모두 삭제 OR 비활성화
ALTER TABLE EMP01 DROP CONSTRAINT EMP01_DEPTNO_FK; --DROP > DISABLE

ALTER TABLE DEPT DISABLE PRIMARY KEY; --참조테이블이 없으므로 해체 처리됨

--DEPT 테이블 PK 생성 및 자녀테이블 외래키 활성화
ALTER TABLE DEPT ENABLE PRIMARY KEY;

ALTER TABLE EMP01 ADD CONSTRAINT EMP01_DEPTNO_FK FOREIGN KEY(DEPTNO) REFERENCES DEPT(ID);
ALTER TABLE EMP03 ADD CONSTRAINT EMP03_DEPTNO_FK FOREIGN KEY (DEPTNO) REFERENCES DEPT(ID);
ALTER TABLE EMP02 ADD CONSTRAINT EMP02_DEPTNO_FK FOREIGN KEY (DEPTNO) REFERENCES DEPT(ID);
----
ALTER TABLE DEPT DISABLE PRIMARY KEY; --참조 외래키 있어서 해제 처리 안됨
--방법2 : DEPT 테이블의 PK 비활성화 시키면서 EMP01~03 함께 비활성화 처리
---------CASCADE 옵션 사용 : 부모테이블 PK + 자녀테이블 FK 동시에 비활성화 처리
ALTER TABLE DEPT DISABLE PRIMARY KEY CASCADE; --CASCADE 참조하고 있는 것들을 해제처리
------------------------------------------------------
/* 제약조건 옵션 : NO DELETE CASCADE
--테이블간의 관계에서 부모테이블(데이터) 삭제시 
  자녀테이블(데이터)도 함께 삭제 처리
********************************/
CREATE TABLE C_TEST_MAIN (
    MAIN_PK NUMBER PRIMARY KEY,
    MAIN_DATA VARCHAR2(30)
    
);

CREATE TABLE C_TEST_SUB ( 
    SUB_PK NUMBER PRIMARY KEY,
    SUB_DATA VARCHAR2(30),
    SUB_FK NUMBER,
    CONSTRAINT C_TEST_SUB_FK FOREIGN KEY (SUB_FK)
    REFERENCES C_TEST_MAIN (MAIN_PK) ON DELETE CASCADE
);

------------------------------
INSERT INTO C_TEST_MAIN VALUES (11111, '1번 메인 데이터');
INSERT INTO C_TEST_MAIN VALUES (22222, '2번 메인 데이터');
INSERT INTO C_TEST_MAIN VALUES (33333, '3번 메인 데이터');
COMMIT;
--
INSERT INTO C_TEST_SUB VALUES (1, '1번 SUB 데이터', 11111);
INSERT INTO C_TEST_SUB VALUES (2, '2번 SUB 데이터', 22222);
INSERT INTO C_TEST_SUB VALUES (3, '2번 SUB 데이터', 33333);
COMMIT;
---메인테이블 데이터 삭제
DELETE FROM C_TEST_MAIN WHERE MAIN_PK = 11111;
COMMIT;
DELETE FROM C_TEST_MAIN WHERE MAIN_PK = 33333;
COMMIT;
SELECT * FROM C_TEST_MAIN;
SELECT * FROM C_TEST_SUB;

--=============

--테이블 삭제 : 부모테이블 - 자녀테이블 관계 설정된 부모테이블 삭제
DROP TABLE C_TEST_MAIN ;
--방법1 : 서브테이블을 모두 삭제하고 부모테이블을 삭제처리
DROP TABLE C_TEST_SUB;
DROP TABLE C_TEST_MAIN ;
--방법2 : 서브테이블에 있는 FK설정을 모두 삭제후에 부모테이블 삭제
-------FK 비활성화 (DISABLE) 설정으로는 안된다.
ALTER TABLE C_TEST_SUB DROP CONSTRAINT C_TEST_SUB_FK;--참조관계 제거
DROP TABLE C_TEST_MAIN;
--방법3 : 부모테이블 삭제시 CASCADE CONSTRAINTS 옵션을 사용
------서브테이블의 제약조건(FK) 삭제후 부모테이블 (MAIN) 삭제 처리
DROP TABLE C_TEST_MAIN CASCADE CONSTRAINTS; --서브테이블 제약조건 제거와 삭제처리 
--==========================================



