/****** 시퀀스(SEQUENCE) *****
SEQUENCE : DB에서 제공하는 자동채번 객체
생성 : CREATE SEQUENCE 시퀀스명;
삭제 : DROP SEQUENCE 시퀀스명;

시퀀스명.NEXTVAL : 시퀀스 번호(값) 생성
시퀀스명.CURRVAL : 현재 시퀀스값 확인(NEXTVAL 한 번 이상 실행 후)
****************************/
CREATE SEQUENCE  "MADANG"."SEQUENCE1"  
MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 
START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
----------

SELECT * FROM BOOK;
SELECT MAX(BOOKID), MAX(BOOKID) + 1 FROM BOOK;

SELECT MAX(BOOKID), NVL(MAX(BOOKID), 0) + 1 FROM BOOK;
SELECT NVL(MAX(BOOKID), 0) + 1 FROM BOOK;


SELECT SEQUENCE1.CURRVAL FROM DUAL; --현재 시퀀스 값 조회
SELECT SEQUENCE1.NEXTVAL FROM DUAL; --새로운 시퀀스 값

--동시에 실행시 문제가 발생하므로 사용된다.

SELECT * FROM BOOK ORDER BY BOOKID DESC;
SELECT MAX(BOOKID) + 1 FROM BOOK;

--BOOK 테이블에 INSERT작업, BOOKID 최대값 + 1
INSERT INTO BOOK
    (BOOKID, BOOKNAME, PUBLISHER, PRICE)
VALUES ((SELECT NVL(MAX(BOOKID), 0) + 1 FROM BOOK),
    'MAX(BOOKID) + 1 취한값', 'ITBOOK', 20000);
----------------
--시퀀스 사용(시작번호 50, NOCACHE)
CREATE SEQUENCE SEQ_BOOK
START WITH 50
INCREMENT BY 1
NOCACHE;

-- BOOK 테이블에 시퀀스 사용해서 입력 처리
INSERT INTO BOOK
    (BOOKID, BOOKNAME, PUBLISHER, PRICE)
VALUES (SEQ_BOOK.NEXTVAL,
    'MAX(BOOKID) + 1 취한값', 'ITBOOK', 20000);
    